<!-- ADD A LEASES FORM-->

<?php
    // include connection to the database
    include('connection.php');
    // to display the navbar in the webpage
    include('navbar.html');
    // including the functions for querying the database
    include('query_functions.php');
    include('alerts.php');

    // fetching records using functions in query_functions.php 
    $all_lease_info = fetch_all("lease_info");
    $all_property_info = fetch_all("property_info");
    $all_unit_info = fetch_all("unit_info");
    $all_persons = fetch_all("persons");

    // repeating above step to fetch records again, this is done to avoid error in retrieving records for selecting manager
    $all_lease_info = fetch_all("lease_info");
    $all_property_info = fetch_all("property_info");
    $all_unit_info = fetch_all("unit_info");
    $all_persons_ = fetch_all("persons");

    // counting current number of records in persons table to generate new id
    $latest_id = count_records("persons");
    $new_id = (int)$latest_id['Count'] + 1;
?>

<!DOCTYPE html>
<head>
    <link rel="stylesheet" type="text/css" href="dashboard.css">
    <link rel="stylesheet" href="add_lease.css">
    <title>Add a Lease Record</title>
</head>
    <!-- Header -->
    <div id="add_lease_header" style="padding-left: 40px;">
    <h1>ADD A LEASE RECORD</h1>
<body>

<!-- Form to collect data for a new lease record -->
<form id="form" action="add_lease.php" method="post" autocomplete="off" style="margin-left: 150px; margin-right: 150px;">

    <!-- Field for parcel number -->
    <p>
        <label for="ParcelNo">Parcel Number: </label>
        <select name="existing_parcel_no" id="existing_parcel_no" required>
            <!-- default option, hints no selection -->
            <option value="" selected disabled hidden>Select</option>
            <!-- fetching parcel numbers to be set as options, value and text displayed is the parcel number -->
            <?php
            while($property = mysqli_fetch_array($all_property_info, MYSQLI_ASSOC)):
            ?>
            <option value="<?php echo $property['ParcelNo']; ?>">
                <?php echo $property['ParcelNo']; ?>
            </option>
            <?php
            endwhile;
            ?>
        </select>
    </p>

    <!-- Field for unit number -->
    <p>
        <label for="UnitNo">Unit Number: </label>
        <select name="existing_unit_no" id="existing_unit_no" required>
        <!-- default option, hints no selection -->
        <option value="" selected disabled hidden>Select</option>
            <!-- fetching parcel numbers to be set as options, value and text displayed is the parcel number -->
            <?php
            while($unit_no = mysqli_fetch_array($all_unit_info, MYSQLI_ASSOC)):
            ?>
            <option value="<?php echo $unit_no['UnitNo']; ?>">
                <?php echo $unit_no['UnitNo']; ?>
            </option>
            <?php
            endwhile;
            ?>
        </select>
    </p>

    <!-- Radio buttons to select if tenant is existing or new -->
    <p>
        <label for="Tenant">Tenant:</label>
        <input type="radio" name="if_existing_tenant" id="existing_tenant" value="existing" style="margin-left: 150px;">Existing
        <input type="radio" name="if_existing_tenant" id="new_tenant" value="new">New
    </p>

    <!-- Div to display if existing tenant is selected, a dropdown to select an ID -->
    <div id="select_tenant">
        <p>
            <label>Tenant ID</label>
            <select name="existing_tenant_id" id="existing_tenant_id" required>
                <!-- default option, hints no selection -->
                <option value="" selected disabled hidden>Select</option>
                <!-- fetching ID to be set as options, value and text displayed is the ID -->
                <?php
                while($person = mysqli_fetch_array($all_persons,MYSQLI_ASSOC)):
                ?>
                <option value="<?php echo $person['ID']; ?>">
                    <?php echo $person['ID']; ?>
                </option>
                <?php
                endwhile;
                ?>

            </select>
        </p>
    </div>

    <!-- Div to display if new tenant is selected, containing a form to be submitted to the persons table-->
    <div id="add_new_tenant">
        <!-- Field for tenant id, autogenerated with js-->
        <p>
            <label for="TenantID">Tenant ID: </label>
            <input type="number" name="new_tenant_id" id="new_tenant_id" value="" readonly required>

            <!-- to pass $new_id to the .js files -->
            <script type="text/javascript">
                var new_id = <?php echo json_encode($new_id); ?>;
            </script>
        </p>

        <!-- Fields for tenant details -->
        <p>
            <label for="Name">Name: </label>
            <input type="text" name="tenant_name" id="tenant_name" required maxlength="30">
        </p>

        <p>
            <label for="Address">Address: </label>
            <input type="text" name="tenant_address" id="tenant_address" required maxlength="80">
        </p>

        <p>
            <label for="GeneralNum">General Number: </label>
            <input type="text" name="tenant_general_num" id="tenant_general_num" required minlength="6" maxlength="15" pattern="^[0-9\-]+$">
        </p>

        <p>
            <label for="EmergencyNum">Emergency Number: </label>
            <input type="text" name="tenant_emergency_num" id="tenant_emergency_num" maxlength="15" pattern="^[0-9\-]*$">
        </p>

        <p>
            <label for="Email">Email: </label>
            <input type="text" name="tenant_email" id="tenant_email" maxlength="50" pattern="[^@\s]+@[^@\s]+\.[^@\s]+">
        </p>
    </div>

    <!-- Field for start of lease -->
    <p>
        <label for="start_of_lease">Start of Lease:</label>
        <input type="text" name="start_of_lease" id="start_of_lease" required onchange="validateDate(this)">
        <small>Format: YYYY-MM-DD</small>
    </p>

    <!-- Field for end of lease -->
    <p>
        <label for="end_of_lease">End of Lease:</label>
        <input type="text" name="end_of_lease" id="end_of_lease" required onchange="validateDate(this)">
        <small>Format: YYYY-MM-DD</small>
    </p>

<!-- Validate date input -->
<script>
        function validateDate(input) {
            const dateRegex = /^\d{4}-\d{2}-\d{2}$/;

            if (!input.value.match(dateRegex)) {
                alert('Invalid date format. Please use the format YYYY-MM-DD.');
                input.value = '';
                return;
            }

            const parts = input.value.split('-');
            const year = parseInt(parts[0]);
            const month = parseInt(parts[1]);
            const day = parseInt(parts[2]);

            const date = new Date(year, month - 1, day);

            if (
                date.getFullYear() !== year ||
                date.getMonth() + 1 !== month ||
                date.getDate() !== day
            ) {
                alert('Invalid date. Please enter a valid date.');
                input.value = '';
            }
        }
</script>

    <!-- Field for total occupants -->
    <p>
        <label for="total_occupants">Total Occupants:</label>
        <input type="text" name="total_occupants" id="total_occupants" required minlength="1" maxlength="2">
    </p>


    <!-- calling the jscripts for executing actions -->
    <!-- depending on whether tenant exists or needs a new record -->
    <script src='isTenantExisting.js'></script>

    <!-- Submit button -->
    <input type="submit" name="submit" value="Submit"></input>
</form>
</body>
</html>
